---
title: "NY Weather Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
```

```{r data_cleaning}
data("ny_noaa")
noaa_data <- ny_noaa %>% 
  janitor::clean_names() %>% 
  separate(date, c("year", "month", "day"), sep = "-") %>% 
  mutate(tmax = as.double(tmax) / 10, 
         tmin = as.double(tmin) / 10, 
         prcp = prcp / 10,
         month = month.name[as.integer(month)], 
         year = as.integer(year)) %>%
  drop_na()
```

```{r data_summarize}
noaa_by_month = 
  noaa_data %>% 
  group_by(year, month) %>% 
  summarize(avg_tmax = round(mean(tmax), 2),
            avg_prcp = round(mean(prcp),2) ) %>%
  mutate(year = as.factor(year),
         month = as.factor(month),
         month = fct_relevel(month, month.name))

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A
Scatter plot of monthly average max temperature v.s. year.
```{r}
noaa_by_month %>%
  mutate(
    text_label = str_c("Average tmax:", avg_tmax, "\nYear: ", year, "\nMonth:", month)) %>% 
  plot_ly(
    x = ~year, y = ~avg_tmax, type = "scatter", mode = "markers",
    color = ~month, text = ~text_label, alpha = 0.5, colors = "viridis")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B
Density plot of monthly average precipitation.
```{r}
p <- plot_ly(colors = "viridis")
for (m in month.name) {
  d <- density(pull(noaa_by_month %>% filter(month == m)))
  p <- add_lines(p, x = d$x, y = d$y, name = m, color = m)
}
p
```

### Chart C
Boxplot of monthly average max temperature.
```{r}
noaa_by_month %>% 
  mutate(month = fct_reorder(month, avg_tmax)) %>% 
  plot_ly(y = ~avg_tmax, color = ~month, type = "box", colors = "viridis")
```

